# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0004_auto_20161101_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpathway',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careerapp.CareerCluster'),
        ),
    ]
