# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0008_clusteractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('cluster', models.ManyToManyField(to='careerapp.CareerCluster')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='Personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Personality'),
        ),
    ]
