# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=200)),
                ('subject2', models.CharField(max_length=200)),
                ('subject3', models.CharField(max_length=200)),
                ('subject4', models.CharField(max_length=200)),
                ('subject5', models.CharField(max_length=200)),
                ('subject6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duration', models.IntegerField(default=4)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Faculty')),
                ('prereq', models.ManyToManyField(blank=True, null=True, to='careerapp.Prerequisite')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Subject'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.School'),
        ),
        migrations.AddField(
            model_name='career',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Programme'),
        ),
    ]
