# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerapp.Programme'),
        ),
    ]
