# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='prereq',
            field=models.ManyToManyField(blank=True, null=True, to='careerapp.Subject'),
        ),
    ]
