# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0002_auto_20161026_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
