# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0003_delete_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Career',
            new_name='CareerCluster',
        ),
        migrations.AddField(
            model_name='programme',
            name='career',
            field=models.ManyToManyField(blank=True, to='careerapp.CareerPathway'),
        ),
    ]
