# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerapp', '0006_auto_20161101_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careercluster',
            name='programme',
        ),
        migrations.AddField(
            model_name='careercluster',
            name='programme',
            field=models.ManyToManyField(to='careerapp.Programme'),
        ),
    ]
